<a href="https://colab.research.google.com/github/DouglasFlint/DeepLearning/blob/main/Tutorial_Padas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src = "https://drive.google.com/uc?id=1KE-uSHGGxJGFZcLVxyM1Fh4JN8PUCIMv" align = "center" >

<font color = 'blue' size = 8>
Tutorial Pandas

<font size=4>
En este Notebook se aborda el uso de la paqueteria Pandas y su utilidad en diversas aplicaciones.

<font color = 'Black' size = 5>
1.- ¿Por qué Pandas?

<font size=4>

Pandas es un herramienta para manipulación y análisis de datos de código abierto, rápida, poderosa, flexible y fácil de utilizar, construida sobre el lenguaje de programación Python.\
Es de uso común en la ciencia de datos y la inteligencia artificial debido a las ventajas y facilidades que proporciona para cargar, preparar, manipular, modelar y analizar datos.

<font size=4>
Algunas características que hacen útil a Pandas son:

<font size=4>
    
1.- Estructuras de datos similares a matrices ($DataFrame$).\
2.- DataFrames similares a los de otros lenguajes de programación.\
3.- Básicamente, los DataFrames son equivalentes a una tabla.\
4.- Los datos en las columnas deben ser del mismo tipo, pero los datos en renglones pueden variar.\
5.- Altamente flexible para tomar datos de múltiples fuentes.

<font size=4> Cualquier cosa que quieras saber de esta biblioteca en el futuro lo puedes encontrar [aquí](https://pandas.pydata.org/docs/user_guide/index.html)

<font size=4>
Importamos la paquetería Pandas:

In [3]:
import pandas as pd
import numpy as np

### Primero vamos a entender las estructuras de datos principales de `Pandas`


# Las series de Pandas


La estructura elemental de panda son las *series*. Para declararlas, se puede usar la función con el constructor por defecto `Series`.

In [4]:
pd.Series(dtype='float64')

Series([], dtype: float64)

Esta estructura de datos es muy parecida a un `np.array` o a una lista de datos en `Python` con la particularidad que existen índices y funciones específicas para manejar la serie. Podemos construir estas series desde una lista, desde un `np.array` o desde un diccionario:

In [5]:
lista = [2, 6, 1, 2.1]
serie_lista=pd.Series(lista)
serie_lista

0    2.0
1    6.0
2    1.0
3    2.1
dtype: float64

In [6]:
diccionario = {'H' : 34, 'o' : 1, 'l' : 0, 'a' : 4, 'M' : "Mundo"}
serie_diccionario = pd.Series(diccionario)
serie_diccionario

H       34
o        1
l        0
a        4
M    Mundo
dtype: object

In [7]:
serie_1 = pd.Series(data=lista, index=['Física', 'Matemáticas', 'Biología','CC'])
serie_1

Física         2.0
Matemáticas    6.0
Biología       1.0
CC             2.1
dtype: float64

# Data Frame

Un Data Frame es una colección de series

In [8]:
tiempo = pd.Series(np.arange(1, 6))
posicion = pd.Series(np.random.randint(0, 10, 5))
componentes = pd.DataFrame({'PrimeraColumna': tiempo, 'SegundaColumna': posicion})
componentes

PrimeraColumna  SegundaColumna
0               1               6
1               2               4
2               3               5
3               4               8
4               5               9

<font color = 'Black' size = 5>
2.- DataFrames (DF)

<font size=4> Para este ejemplo se utilizó la base de datos **Superconductivty Data Data Set** del repositorio:

[UCI Machine Learning Repository: Superconductivty Data Data Set ](https://archive.ics.uci.edu/ml/datasets/Superconductivty+Data)

<font size=4> 
Hay dos archivos: 

(1) train.csv: contiene 81 características extraídas de 21263 superconductores junto con la temperatura crítica en la columna 82, 


(2) unique_m.csv: contiene la fórmula química dividida para todos los 21263 superconductores del archivo  train.csv 



Las dos últimas columnas tienen la temperatura crítica y la fórmula química. 
    
**El objetivo de este trabajo fue es predecir la temperatura crítica en función de las características extraídas.**

# Conectar Colab con Google Drive



In [9]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [11]:
# Crear enlace simbólico entre la dirección /content/gdrive/My\ Drive/ que ahora equivale a /mydrive
!ln -s /content/gdrive/My\ Drive/ /mydrive
!ls /mydrive

'Amir D. Aczel - Entrelazamiento_ El Mayor Misterio de la Fisica.rar'
'Asesoria 1. Sucesiones - 4014 (2020-04-30 at 12:10 GMT-7)'
'Asistentes práctica de campo..gsheet'
'Avances del proyecto.pdf'
 Benton_2005_vertebrate_palaeontology_1.pdf
'Brian Greene - El Universo Elegante_ Supercuerdas, Dimensiones Ocultas y Busqueda Teoria Final   The Elegant Universe (Spanish Edition)-Critica (2001).epub'
'Brian Greene - The Fabric of the Cosmos-Vintage (2005).pdf'
 Cap8.mov
 capitulo10.mov
 Classroom
'Colab Notebooks'
 CRABPPPT.pptx
'credencialCT (1).pdf'
 credencialCT.pdf
 credencial.pdf
 datosyblogpdf.pdf
 Ej1-3Cal3.pdf
 Ej4Ex.pdf
 Ej5Ex.pdf
 Ej6Ex.pdf
 Examen1Cal4PLDE.pdf
'Examen1Proba (1).pdf'
 exoplanet.eu_catalog.gsheet
 exoplanet.eu_catalog.xlsx
'Feynman R. - Surely you'\''re joking, Mr. Feynman (bad typesetting) (1997).pdf'
 historial.pdf
 inscripcion-20211.pdf
'Leon M. Lederman, Christopher T. Hill - Symmetry and the Beautiful Universe-Prometheus Books (2004).pdf'
 linear_reg.gdoc
'Mic

In [18]:
# Desplegar información de archivos en tal directorio
!ls  /content/gdrive/MyDrive/


'Amir D. Aczel - Entrelazamiento_ El Mayor Misterio de la Fisica.rar'
'Asesoria 1. Sucesiones - 4014 (2020-04-30 at 12:10 GMT-7)'
'Asistentes práctica de campo..gsheet'
'Avances del proyecto.pdf'
 Benton_2005_vertebrate_palaeontology_1.pdf
'Brian Greene - El Universo Elegante_ Supercuerdas, Dimensiones Ocultas y Busqueda Teoria Final   The Elegant Universe (Spanish Edition)-Critica (2001).epub'
'Brian Greene - The Fabric of the Cosmos-Vintage (2005).pdf'
 Cap8.mov
 capitulo10.mov
 Classroom
'Colab Notebooks'
 CRABPPPT.pptx
'credencialCT (1).pdf'
 credencialCT.pdf
 credencial.pdf
 datosyblogpdf.pdf
 Ej1-3Cal3.pdf
 Ej4Ex.pdf
 Ej5Ex.pdf
 Ej6Ex.pdf
 Examen1Cal4PLDE.pdf
'Examen1Proba (1).pdf'
 exoplanet.eu_catalog.gsheet
 exoplanet.eu_catalog.xlsx
'Feynman R. - Surely you'\''re joking, Mr. Feynman (bad typesetting) (1997).pdf'
 historial.pdf
 inscripcion-20211.pdf
'Leon M. Lederman, Christopher T. Hill - Symmetry and the Beautiful Universe-Prometheus Books (2004).pdf'
 linear_reg.gdoc
'Mic

In [20]:
# Copiar archivos.csv a /content/
!cp /content/gdrive/MyDrive/unique_m.csv /content/
!cp /content/gdrive/MyDrive//train.csv /content/

<font size=4> Levantamos el archivo CSV con pandas:

In [21]:
df = pd.read_csv('train.csv')

#Mostramos el DataFrame
print(type(df))
print("\n")
df

<class 'pandas.core.frame.DataFrame'>




number_of_elements  mean_atomic_mass  ...  wtd_std_Valence  critical_temp
0                       4         88.944468  ...         0.437059          29.00
1                       5         92.729214  ...         0.468606          26.00
2                       4         88.944468  ...         0.444697          19.00
3                       4         88.944468  ...         0.440952          22.00
4                       4         88.944468  ...         0.428809          23.00
...                   ...               ...  ...              ...            ...
21258                   4        106.957877  ...         0.496904           2.44
21259                   5         92.266740  ...         0.212959         122.10
21260                   2         99.663190  ...         0.400000           1.98
21261                   2         99.663190  ...         0.462493           1.84
21262                   3         87.468333  ...         1.500000          12.80

[21263 rows x 82 columns]

<font size=4> Podemos verificar las dimensiones del DataFrame con el atributo **.shape** como en los arreglos de Python.

In [22]:
df.shape

(21263, 82)

<font size=4> Observamos que tenemos 21263 superconductores y 82 rasgos (features) de cada uno.

<font size=4> Podemos visualizar los primeros $n$ renglones con el atributo **.head(n)** y los últimos $m$ con **.tail(m)** de la siguiente manera:

In [23]:
n = 10 
df.head(n)

number_of_elements  mean_atomic_mass  ...  wtd_std_Valence  critical_temp
0                   4         88.944468  ...         0.437059           29.0
1                   5         92.729214  ...         0.468606           26.0
2                   4         88.944468  ...         0.444697           19.0
3                   4         88.944468  ...         0.440952           22.0
4                   4         88.944468  ...         0.428809           23.0
5                   4         88.944468  ...         0.410326           23.0
6                   4         88.944468  ...         0.349927           11.0
7                   4         76.517718  ...         0.444697           33.0
8                   4         76.517718  ...         0.440952           36.0
9                   4         76.517718  ...         0.437059           31.0

[10 rows x 82 columns]

In [24]:
m = 5
df.tail(m)

number_of_elements  mean_atomic_mass  ...  wtd_std_Valence  critical_temp
21258                   4        106.957877  ...         0.496904           2.44
21259                   5         92.266740  ...         0.212959         122.10
21260                   2         99.663190  ...         0.400000           1.98
21261                   2         99.663190  ...         0.462493           1.84
21262                   3         87.468333  ...         1.500000          12.80

[5 rows x 82 columns]

<font size=4> Podemos renombrar una columna en particular utilzando el atributo **.rename()**

In [25]:
# Cambiamos el nombre de la columna "number_of_elements" 
# por "numero_de_elementos"

df.rename(columns = {"number_of_elements":"numero_de_elementos"}, inplace = True)  

                                                                                   
df.head(5)

numero_de_elementos  mean_atomic_mass  ...  wtd_std_Valence  critical_temp
0                    4         88.944468  ...         0.437059           29.0
1                    5         92.729214  ...         0.468606           26.0
2                    4         88.944468  ...         0.444697           19.0
3                    4         88.944468  ...         0.440952           22.0
4                    4         88.944468  ...         0.428809           23.0

[5 rows x 82 columns]

<font size=4> Podemos acceder a información de las columnas del dataframe mediante el atributo **df.column_name** o mediante la instrucción **df['column_name']**

In [26]:
#Utilizamos cada uno de los comandos:

print(type(df.numero_de_elementos))
df.numero_de_elementos

<class 'pandas.core.series.Series'>


0        4
1        5
2        4
3        4
4        4
        ..
21258    4
21259    5
21260    2
21261    2
21262    3
Name: numero_de_elementos, Length: 21263, dtype: int64

In [27]:
print(type(df["numero_de_elementos"]))
df["numero_de_elementos"]


<class 'pandas.core.series.Series'>


0        4
1        5
2        4
3        4
4        4
        ..
21258    4
21259    5
21260    2
21261    2
21262    3
Name: numero_de_elementos, Length: 21263, dtype: int64

# Sugerencia/Consejo: 

## Al trabajar con cuenstiones numéricas es preferible trabajar con **arrays** que con  **DataFrames**.

Para ello, cuando se tiene un DataFrame podemos acceder a su representación Numpy con el campo**.values**

In [28]:
#Utilizamos cada uno de los comandos:

print(type(df.numero_de_elementos.values))
df.numero_de_elementos

<class 'numpy.ndarray'>


0        4
1        5
2        4
3        4
4        4
        ..
21258    4
21259    5
21260    2
21261    2
21262    3
Name: numero_de_elementos, Length: 21263, dtype: int64

<font size=4> Podemos extraer información de un renglón específico del $DataFrame$  (index) mediante **series** con el atributo **.loc[ ]**:

In [29]:
df.loc[524]  #Utilizamos el atributo .loc()

numero_de_elementos       4.000000
mean_atomic_mass         96.032850
wtd_mean_atomic_mass     58.347829
gmean_atomic_mass        69.515930
wtd_gmean_atomic_mass    37.476574
                           ...    
range_Valence             1.000000
wtd_range_Valence         0.816101
std_Valence               0.433013
wtd_std_Valence           0.269624
critical_temp            85.000000
Name: 524, Length: 82, dtype: float64

<font size=4> Se puede acceder a información en particular utilizando los métodos previos, si por ejemplo queremos obtener la temperatura crítica del superconductor 524:

In [30]:
df['critical_temp'][524]

85.0

<font size=4> En pandas se utilizan también los **operadores de acceso** como el atributo **.iloc[]** que basa su operación en la enumeración de renglones y columnas de Python

<font size=4> Si por ejemplo buscamos la información del superconductor **i-ésimo**, entonces utilizamos **df.iloc[ i ]** el cual obtiene la información del renglón **i-esimo**.

In [31]:
df.iloc[524]

numero_de_elementos       4.000000
mean_atomic_mass         96.032850
wtd_mean_atomic_mass     58.347829
gmean_atomic_mass        69.515930
wtd_gmean_atomic_mass    37.476574
                           ...    
range_Valence             1.000000
wtd_range_Valence         0.816101
std_Valence               0.433013
wtd_std_Valence           0.269624
critical_temp            85.000000
Name: 524, Length: 82, dtype: float64

<font size=4> Si queremos obtener el numero de elementos (columna 0) de todos los superconductores:

In [32]:
df.iloc[:, 0]

0        4
1        5
2        4
3        4
4        4
        ..
21258    4
21259    5
21260    2
21261    2
21262    3
Name: numero_de_elementos, Length: 21263, dtype: int64

<font size=4> Si queremos obtener el número de elementos y su temperatura crítica de los superconductores 0 y 524:

In [33]:
df.iloc[[0,524],  [0,81]]

numero_de_elementos  critical_temp
0                      4           29.0
524                    4           85.0

<font size=4> Como se puede observar, el atributo **.iloc[]** utiliza el índice o posición del superconductor (los renglones en este caso) o las columnas para operar. De distinta manera, **.loc[]** basa su operación en el nombre del índice de los datos, no en su posición o enumeración de Python:

<font size=4> Si queremos obtener el numero de elementos en el superconductor 524:

In [34]:
df.loc[524, 'numero_de_elementos']

4

<font size=4> Si quieremos obtener el numero de elementos de los superconductores 524 y 342 por ejemplo:

In [35]:
df.loc[[524, 342], 'numero_de_elementos']

524    4
342    4
Name: numero_de_elementos, dtype: int64

<font size=4> Si quieremos obtener el numero de elementos (columna 0) y temperatura crítica (columna 85) de cada uno de los superconductores:

In [36]:
df.loc[:, ['numero_de_elementos', "critical_temp"]]

numero_de_elementos  critical_temp
0                        4          29.00
1                        5          26.00
2                        4          19.00
3                        4          22.00
4                        4          23.00
...                    ...            ...
21258                    4           2.44
21259                    5         122.10
21260                    2           1.98
21261                    2           1.84
21262                    3          12.80

[21263 rows x 2 columns]

##  Pandas también puede utilizar **operadores lógicos** como **==**, **<** y **>**.

<font size=4> Si queremos obtener los superconductores con temperatura crítica iguala 85 K hacemos lo siguiente:

In [37]:
df.loc[df.critical_temp == 85]

numero_de_elementos  mean_atomic_mass  ...  wtd_std_Valence  critical_temp
44                       4         90.278600  ...         0.339935           85.0
96                       4         95.450680  ...         0.257539           85.0
215                      5         66.551958  ...         0.290364           85.0
321                      5         80.180280  ...         1.076923           85.0
390                      5         72.894330  ...         0.266375           85.0
...                    ...               ...  ...              ...            ...
9578                     5         88.936744  ...         0.267224           85.0
9580                     5         88.936744  ...         0.266563           85.0
9867                     4         93.530600  ...         0.273056           85.0
10107                    5        101.732610  ...         0.526783           85.0
19619                    9        106.879678  ...         0.377957           85.0

[83 rows x 82 columns]

<font size=4> Si queremos obtener los superconductores con temperatura crítica menor a 85 K hacemos lo siguiente:

In [ ]:
df.loc[df.critical_temp < 85]

<font size=4> Si queremos los superconductores con temperatura crítica de 83 o de 85 K

In [ ]:
df.loc[df.critical_temp.isin( [83, 85] )]

<font size=4> Si queremos identificar todas las posiciones en el dataframe que tienen un valor vacío o **"NaN"**

In [38]:
df.loc[df.critical_temp.isnull()].shape
#df.loc[df.critical_temp.notnull()].shape

(0, 82)

<font size=4> Pandas también puede calcular promedios, desviación estándar, etc. y otras funciones útiles, por ejemplo:

<font size=4> El atributo **.describe()** nos da la siguiente información de cada una de las columnas del dataframe:

In [39]:
df.describe()

numero_de_elementos  mean_atomic_mass  ...  wtd_std_Valence  critical_temp
count         21263.000000      21263.000000  ...     21263.000000   21263.000000
mean              4.115224         87.557631  ...         0.673987      34.421219
std               1.439295         29.676497  ...         0.455580      34.254362
min               1.000000          6.941000  ...         0.000000       0.000210
25%               3.000000         72.458076  ...         0.306892       5.365000
50%               4.000000         84.922750  ...         0.500000      20.000000
75%               5.000000        100.404410  ...         1.020436      63.000000
max               9.000000        208.980400  ...         3.000000     185.000000

[8 rows x 82 columns]

<font size = 4> Si queremos sólo la información de la temperatura crítica:

In [40]:
df.critical_temp.describe()

count    21263.000000
mean        34.421219
std         34.254362
min          0.000210
25%          5.365000
50%         20.000000
75%         63.000000
max        185.000000
Name: critical_temp, dtype: float64

<font size=4> El atributo **.mean()** nos regresa el promedio, en este caso, de cada columna:

In [41]:
#df.critical_temp.mean()

df.mean()

numero_de_elementos       4.115224
mean_atomic_mass         87.557631
wtd_mean_atomic_mass     72.988310
gmean_atomic_mass        71.290627
wtd_gmean_atomic_mass    58.539916
                           ...    
range_Valence             2.041010
wtd_range_Valence         1.483007
std_Valence               0.839342
wtd_std_Valence           0.673987
critical_temp            34.421219
Length: 82, dtype: float64

<font size=4> El atributo **.unique()** nos regresa los valores posibles que puede tomar un elemento sin repetir:

In [42]:
df.numero_de_elementos.unique()

array([4, 5, 6, 3, 7, 2, 8, 9, 1])

<font size = 5> Por otro lado, el archivo **unique_m.csv** contiene la composición por elemento de cada uno de los superconductores así como su fórmula.

In [43]:
df_2 = pd.read_csv('unique_m.csv')
df_2

H  He   Li   Be  ...  At  Rn  critical_temp                material
0      0.0   0  0.0  0.0  ...   0   0          29.00         Ba0.2La1.8Cu1O4
1      0.0   0  0.0  0.0  ...   0   0          26.00  Ba0.1La1.9Ag0.1Cu0.9O4
2      0.0   0  0.0  0.0  ...   0   0          19.00         Ba0.1La1.9Cu1O4
3      0.0   0  0.0  0.0  ...   0   0          22.00       Ba0.15La1.85Cu1O4
4      0.0   0  0.0  0.0  ...   0   0          23.00         Ba0.3La1.7Cu1O4
...    ...  ..  ...  ...  ...  ..  ..            ...                     ...
21258  0.0   0  0.0  0.0  ...   0   0           2.44      Tm0.84Lu0.16Fe3Si5
21259  0.0   0  0.0  0.0  ...   0   0         122.10         Tl1Ba2Ca3Cu4O11
21260  0.0   0  0.0  0.0  ...   0   0           1.98              Nb0.8Pd0.2
21261  0.0   0  0.0  0.0  ...   0   0           1.84            Nb0.69Pd0.31
21262  0.0   0  0.0  0.0  ...   0   0          12.80           Fe1Se0.2Te0.8

[21263 rows x 88 columns]

<font size=4> Si queremos agregar a nuestro dataframe original la columna **material** que aparece en este nuevo archivo, hacemos lo siguiente:

In [44]:
df["compuesto"] = df_2["material"]

In [45]:
df

numero_de_elementos  ...               compuesto
0                        4  ...         Ba0.2La1.8Cu1O4
1                        5  ...  Ba0.1La1.9Ag0.1Cu0.9O4
2                        4  ...         Ba0.1La1.9Cu1O4
3                        4  ...       Ba0.15La1.85Cu1O4
4                        4  ...         Ba0.3La1.7Cu1O4
...                    ...  ...                     ...
21258                    4  ...      Tm0.84Lu0.16Fe3Si5
21259                    5  ...         Tl1Ba2Ca3Cu4O11
21260                    2  ...              Nb0.8Pd0.2
21261                    2  ...            Nb0.69Pd0.31
21262                    3  ...           Fe1Se0.2Te0.8

[21263 rows x 83 columns]

<font size=4> Observamos que se agregó la columna **material** ahora con el nombre **compuesto**.